server:
  port: 8081
girl:
  love:
    cupSize: A
    age: 18
spring:
  redis:
    host: 106.14.187.139
    port: 6379
    timeout: 20000
    database: 1
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1